'use client'
import Head from 'next/head'

import axios from 'axios'
import { useEffect } from 'react'
import { useTheme } from '@emotion/react'
import { Typography } from '@mui/material'

export default function Home() {
  const fetchApiUser = async () => {
    await axios.get("https://api-shop-lks2.onrender.com/api/users?limit=10&page=1&order=created%20asc")
      .then((res) => console.log("res", res))
  }
  useEffect(() => {
    fetchApiUser()
  }, [])

  const theme = useTheme()
  console.log("theme", { theme })

  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography >Hello world check deploy</Typography>
    </>
  )
}
